Add status (stopped, running, initialized) to listInstances
clusterio/factorioClusterio pull request #312
Opened 2020-08-30 19:02 UTC by Danielv123

as discussed in discord.

2020-08-30 19:04 UTC, psihius approved these changes

2020-08-30 19:26 UTC, Hornwitser requested changes
There seems to be a missing component here.  If you start up a master and list its instances before the slave the instances are on connects, the status is undefined.  That should not happen, the status should be well defined in all cases.

I suggest adding two more statuses to be possible for instances: `unknown` and `unassigned`.  Additionally: 
- In `updateInstancesEventHandler` there's a case where an instance is set with db.instances.set which doesn't include the status, it should be set to the status received from the slave.
- In `createInstanceRequestHandler` the newly created instance should have status `unassigned`.
- In `loadInstances` the loaded instance should have status `unknown` if `instance.config.get("instance.assigned_slave")` is non null, otherwise `unassigned`.

2020-08-30 19:26 UTC, Hornwitser commented on lib/link/messages.js
> +					"status": { enum: ["stopped", "initialized", "running"] },
This should be added to the required list a few lines up in the schema as well.  I've usually added the type parameter for enum validated items, though I see the updateInstances event has it without `type: "string"` as well.

2020-09-28 04:54 UTC, psihius commented
@Danielv123 So what's the status on this one then?

2020-09-28 08:29 UTC, Danielv123 commented
I believe this PR might have broken due to the reorganization PR being merged, but it’s a 2 line change. It is important as the web interface doesn’t make much sense without this functionality (having to press start instance to get an error about instance already started is just horrible UX), but I don’t believe we ever came to an agreement about how to define all the undefined behavior.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Arvids Godjuks<mailto:notifications@github.com>
Sent: Monday, September 28, 2020 06:54
To: clusterio/factorioClusterio<mailto:factorioClusterio@noreply.github.com>
Cc: Daniel<mailto:danielv@live.no>; Mention<mailto:mention@noreply.github.com>
Subject: Re: [clusterio/factorioClusterio] Add status (stopped, running, initialized) to listInstances (#312)


@Danielv123<https://github.com/Danielv123> So what's the status on this one then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/clusterio/factorioClusterio/pull/312#issuecomment-699768720>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABT2MLLNB4T7HOUVRWTJX6DSIAJJXANCNFSM4QPY3Z7Q>.

2020-09-28 15:07 UTC, Hornwitser commented
I can redo this with the changes I've suggested later today.  It would make the status much more sensible than the code here.

2020-09-29 07:02 UTC, closed without merging